apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # Allow only one node to read/write. Other options ReadOnlyMany, ReadWriteMany
  resources:
    requests:
      storage: 2Gi