apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # Connect to Letsencrypt Staging Server
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'kuldeepsingh82@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-staging # This is where letsencrypt share the key during the communication
    http01: {} # Method to connect to letsencrypt (http01 in this case)

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # Connect to Letsencrypt Prod Server
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'kuldeepsingh82@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod # This is where letsencrypt share the key during the communication
    http01: {} # Method to connect to letsencrypt (http01 in this case)
